Week 3
OlgaKovalevskayaa/c-gallery pull request #3
Opened 2023-01-11 20:01 UTC by OlgaKovalevskayaa

У меня косяк с отображением комментариев.  Они все отображаются на каждой фотке. 
И мне кажется, что ты меня будешь ругать за фетч в фетче), потому что я сама уже путаюсь в своем коде

2023-01-12 21:33 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                    const ghjk = get(item.text)
Что за нейминг?

2023-01-12 21:33 UTC, PolinaShneider commented on scripts/getting_posts.js
> +            function openModal(image, text, tags, created_at, id, likes, comments) {
Не хочешь деструктурировать объект прямо в параметрах?

2023-01-12 21:34 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                let DELETE = `https://c-gallery.polinashneider.space/api/v1/users/me/posts/${id}/`;
Константы надо через const, и вынеси их на самый верх файла

2023-01-12 21:34 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                            alert('Попробуйте в другой раз');
Давай нормальное уведомление покажем, а не alert

2023-01-12 21:35 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                            alert('Пост успешно удален');
У тебя есть уведомления, используй их. alert редко используется в продакшен, так как он некрасивый, зависит от браузера, и его никак не кастомизировать

2023-01-12 21:36 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                                alert('Вы забыли ввести текст');
Тут можно без алерта, просто ничего не добавлять

2023-01-12 21:57 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                                commentsItem.textContent = postCommentText;
У тебя все комментарии добавляются в одно место из-за того что подставляешь их в commentsItem. По логике отрисовка комментариев должна быть внутри openModal, так как это тоже контент модалки. Форматирование даты я бы тоже туда утащила

2023-01-12 21:59 UTC, PolinaShneider commented on scripts/getting_posts.js
> +export function gettingPosts() {
У тебя просто огромнейшая функция. Внутри есть функции поменьше — это хорошо, но нужна ли эта внешняя?

2023-01-12 22:00 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                const date1 = new Date(item.created_at);
Давай по возможности без цифр в именах переменных

2023-01-12 22:00 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                let year = date1.getFullYear();
Это можно вынести в отдельную функцию для форматирования даты, и здесь ее просто вызвать

2023-01-12 22:01 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                    clonPost.querySelector(".comments__item-nickname").textContent = 'No name';
По идее комментарии ты оставляешь с текущего аккаунта, и неважно что там заглушка. Поэтому аватарка должна быть школы и никнейм тоже

2023-01-12 22:01 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                    console.log(item.text);
Не должно бывать вывода в консоль вообще

2023-01-12 22:04 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                    clonPost.querySelector(".comments__item-nickname").textContent = 'No name';
"Рыбный" комментарий удалить. Комментарии не должны быть вложенными. То есть пусть все отображаются на одном уровне
<img width="523" alt="image" src="https://user-images.githubusercontent.com/15448200/212190991-682f83b7-6d56-4619-9e2b-95d54a6876dc.png">

2023-01-15 19:02 UTC, OlgaKovalevskayaa commented on scripts/getting_posts.js
> +                    clonPost.querySelector(".comments__item-nickname").textContent = 'No name';
Что-то не так. Я вроде исправила, но все ровно большой комментарий нормально отображается, а маленький нет. 
![Снимок экрана (105)](https://user-images.githubusercontent.com/110782966/212561575-19f362af-2eb1-47ae-add6-fb0c7f14bce3.png)

2023-01-15 20:41 UTC, OlgaKovalevskayaa commented on scripts/getting_posts.js
> +                    clonPost.querySelector(".comments__item-nickname").textContent = 'No name';
Может дело в этом.
Я отключила justify-content: center и все встало как надо.
![Снимок экрана (106)](https://user-images.githubusercontent.com/110782966/212566070-ff8779f9-6e08-403f-83a6-4c6fc1e6fc63.png)

2023-01-17 17:05 UTC, OlgaKovalevskayaa commented on scripts/getting_posts.js
> +                            alert('Пост успешно удален');
.catch(() => {})
а я могу эту строку оставить пустой?
в настоящем инстаграме ведь нет уведомления

2023-01-17 17:09 UTC, OlgaKovalevskayaa commented on scripts/getting_posts.js
> +                            alert('Попробуйте в другой раз');
.catch(() => {})
а я могу эту строку оставить пустой, в настоящем инстаграме ведь нет уведомления ?

2023-01-18 13:30 UTC, OlgaKovalevskayaa commented on scripts/getting_posts.js
> +                let DELETE = `https://c-gallery.polinashneider.space/api/v1/users/me/posts/${id}/`;
я их не выносила, потому что ${id} внутри них - внутренняя переменная и она перестанет работать ведь, если вынесу

2023-01-18 13:31 UTC, OlgaKovalevskayaa commented on scripts/getting_posts.js
> +            function openModal(image, text, tags, created_at, id, likes, comments) {
ещё здесь не исправляла, но сделаю, когда разберусь с комментариями

2023-01-18 13:34 UTC, OlgaKovalevskayaa commented on scripts/getting_posts.js
> +export function gettingPosts() {
да, скорее всего она не нужна
я просто пока не очень понимаю,  как мне без этой внешней функции придется экспортировать много всего и пока обернула все в одну

2023-01-19 19:09 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                            alert('Попробуйте в другой раз');
Не должно быть алертов. Используй красивые уведомления, которые у тебя есть в верстке

2023-01-19 19:11 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                            if (postCommentText == '') {
Почему ты проверяешь на пустоту уже после получения ответа с сервера? При такой логике у тебя пишется в базу комментарий без текста. Эта проверка должна быть еще до отправки запроса

2023-01-19 19:11 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                                alert("Запись успешно внесена");
Пользуешься инстаграмом? Там комментарий к посту добавляется сразу без перезагрузки страницы. Вместо алерта можешь делать append в верстку

2023-01-19 19:13 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                item.comments.forEach((item) => {
У тебя отображаются все комментарии во всех постах из-за этой строчки кода. Модалка одна, а в item окажется по очереди каждый пост, и из-за этого путаница

2023-01-19 19:14 UTC, PolinaShneider commented on scripts/getting_posts.js
> +            function openModal(image, text, tags, created_at, id, likes, comments_length) {
Перенеси отображение комментариев сюда. Передавай в качестве одного из параметров не comments.length, а просто свойство comments

2023-01-19 19:14 UTC, PolinaShneider commented on scripts/getting_posts.js
> +                                //commentsItem.textContent = postCommentText;
Не должно быть закомментированного кода

2023-01-19 19:15 UTC, PolinaShneider requested changes
Нужно убрать все алерты и заменить на красивые уведомления. Также комментарий должен добавляться сразу (то есть без перезагрузки страницы)

2023-01-19 19:16 UTC, PolinaShneider commented on scripts/getting_posts.js
> +import { AUTHORIZATION, ADDRESS_GET, body, bodyOverlay, COMMENTS, alertSuccess } from './main.js'
Лучше назови файл `getting-posts.js`. Через нижнее подчеркивание редко называют файлы

2023-01-21 16:27 UTC, OlgaKovalevskayaa commented on scripts/getting_posts.js
> +export function gettingPosts() {
Я не совсем понимаю здесь. 
я сделала одну большую внешнюю чтобы сделать экспорт, по другому не получается fetch экспортировать

2023-01-21 16:33 UTC, OlgaKovalevskayaa commented on scripts/getting_posts.js
> +            function openModal(image, text, tags, created_at, id, likes, comments) {
Если я правильно поняла, то вроде деструктурировала

2023-01-22 18:12 UTC, PolinaShneider commented on scripts/getting-posts.js
> +    const commentСontent = getComent(postCommentText, 'codegirl_school', 'https://c-gallery.polinashneider.space/images/avatar.svg', new Date);
Не вызывай конструкторы без скобок, несмотря на то что язык это позволяет. Нужно писать `new Date()`

2023-01-22 18:13 UTC, PolinaShneider commented on scripts/getting-posts.js
> +    commentsContent.append(commentСontent)
Комментарии добавляются, но счетчик их без перезагрузки страницы не обновляется
<img width="534" alt="image" src="https://user-images.githubusercontent.com/15448200/213932655-e7a44104-4ace-48e1-8d47-7a9e4b96caa7.png">

2023-01-22 18:21 UTC, PolinaShneider commented on scripts/getting-posts.js
> +//const DELETE = `https://c-gallery.polinashneider.space/api/v1/users/me/posts/${id}/`;
Не должно быть закомментированного кода

2023-01-22 18:21 UTC, PolinaShneider commented on scripts/getting-posts.js
> +    if (hours < 10) {
Этот код вижу в четырех местах. Напрашивается вынесение в функцию

2023-01-22 18:22 UTC, PolinaShneider commented on scripts/getting-posts.js
> +    const commentСontent = getComent(postCommentText, 'codegirl_school', 'https://c-gallery.polinashneider.space/images/avatar.svg', new Date);
Адрес аватарки в константу

2023-01-22 18:22 UTC, PolinaShneider commented on scripts/getting-posts.js
> +                    const id = parametr;
Эта функция точно нужна? Выглядит так, что можно без нее. Она получает значение и тут же возвращает его

2023-01-22 18:24 UTC, PolinaShneider commented on scripts/getting-posts.js
> +                    emptyStringCheck()
В emptyStringCheck у тебя есть return, но возвращаемое значение не используется. Из-за этого может быть не зачтен один из критериев

2023-01-22 18:24 UTC, PolinaShneider commented on scripts/getting-posts.js
> +                        .then(() => {})
Нужен ли здесь пустой then?

2023-01-22 18:25 UTC, PolinaShneider reviewed
Отличная работа) Осталось кое-что по мелочи поправить, и все

2023-01-24 21:00 UTC, PolinaShneider commented on scripts/getting-posts.js
> +const commentAvatar = 'https://c-gallery.polinashneider.space/images/avatar.svg';
Константы должны быть записаны капсом

2023-01-24 21:01 UTC, PolinaShneider commented on scripts/getting-posts.js
> +    let date = newDate.getDate();
Все что можно объявить через const, нужно объявлять через const

2023-01-24 21:02 UTC, PolinaShneider commented on scripts/getting-posts.js
> +            photoCount.textContent = `${counter}`;
Тут не нужны косые кавычки

2023-01-24 21:03 UTC, PolinaShneider commented on scripts/getting-posts.js
> +                addPost.addEventListener("click", () => {
Здесь обработчики добавляются в цикле — не будет зачтен критерий про делегирование. Но в принципе можешь оставить текущий вариант.

2023-01-24 21:05 UTC, PolinaShneider commented on scripts/getting-posts.js
> +                    emptyStringCheck()
emptyStringCheck возвращает значение — у тебя не будет зачтен соответствующий критерий. Если просто в ифе там напишешь return без значения, поведение интерфейса не изменится, а код будет логичнее

2023-01-24 21:05 UTC, PolinaShneider commented on scripts/main.js
> +    }, 2000);
Таймаут в константу

2023-01-25 14:19 UTC, OlgaKovalevskayaa commented on scripts/getting-posts.js
> +                addPost.addEventListener("click", () => {
(( а как должно быть?
кажется, у меня проблемы с делегированием

2023-01-25 16:13 UTC, closed without merging